version: '3'
services:
  jekyll:
    build:
      context: . # Use the current directory for the build context
      dockerfile: Dockerfile
    image: qwm # Default image name
    ports:
      - "4000:4000"
    volumes:
      - "$PWD:/srv/jekyll"
      - ./vendor/bundle/:/usr/local/bundle
    command: bundle exec jekyll serve --force_polling --drafts --host 0.0.0.0
    # command: ["bundle", "exec", "jekyll", "serve",  "--force_polling" , "--host", "0.0.0.0"]