version: '3'
services:
  jekyll:
    image: qwm
    ports:
      - "4000:4000"
    volumes:
      - "./:/srv/jekyll"
    command: ["bundle", "exec", "jekyll", "serve",  "--force_polling" , "--host", "0.0.0.0"]
    # command: ["jekyll", "serve",  "--watch", "--incremental" , "--host", "0.0.0.0"]